---
language: node_js
node_js:
  - 'lts/*'
cache: yarn
script:
  - yarn lint
  - yarn generate
notifications:
  email: false
  slack:
    secure: Hvf/KINKvu4xWn6OMAYtNVDIoX3NQ4MahP0gN6dF4GjSXhj+sNjDRIwf1a/HExhNpYfJ9FtqAHDBfnuyyGsSjvv3H4gWYkRnUSGzgeYhRkV2dL+tqnJeAEkfncrz4+lXbz6lKBY5pigB5XGIGaPUW5qLoL62WGv9FsdX/7DYwjMyn8iO1QWLzDd+6WShM3qDSN2JQFpsNoKPRp36oOAMOSxKQIvOptEY1JA0qXa43BfOaupLtVw0pXb5dRtzp6EQaVTGSGJ8JPImRg546O7xIwONgxSh5KzBPR63DBUyH5230ufNyGEZormob9rezDpzbOXdnomAs7gqWtv9gYhjb7JMNVip19WSypq3P06r3G1uCOlxeQRvscr/QG/yx8LRosVXj23QB9/VtXz4/l/WJQdO1ors4Mhb5emRSgpTgCb5zHJ7CK1RVw+jLkQN273NG8fSTyDUpLh2rHOCwum2LwIdnpmLxcwPKUpXcCsd0vczwGcwiuufcsttnwvmNq/PpaJHsMP7f+O1uAzSrQJMg89KIiPzu2AE3yPU8UI8H02iVpDJnESPw5XjsdETAzmefXXFOLjgddTaOWl+QUEq9POukmBZtx3FdKSt+R5c7S3spyvzfTTEg0UEN7Y47noHcXyKXkSTZ9R9JYsj7tmixDbW9NKjbW9RBTjEhQuD3sk=
